# Generated by Django 4.2.4 on 2024-02-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
