# Generated by Django 4.2.4 on 2024-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/alumni/')),
                ('deskripsi', models.CharField(blank=True, max_length=1000, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('sekolah', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.AlterModelOptions(
            name='dataguru',
            options={'verbose_name_plural': 'Data Guru'},
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='image',
            field=models.ImageField(upload_to='images/tendik/'),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
