# Generated by Django 4.2.4 on 2024-02-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alumni_alter_dataguru_options_alter_dataguru_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumni',
            new_name='AlumniLK',
        ),
        migrations.AlterModelOptions(
            name='alumnilk',
            options={'verbose_name_plural': 'Alumni LK'},
        ),
    ]
